ScriptSim:
  ros__parameters:
    points:   
      # [moving_type, x, y, w] - moving_type: path, dock, or wait(x for seconds)
      # TODO: Fix the dock

      - [path, 0.9, 0.8, 0.707, 0.707]
      - [path, 0.9, 0.8, 0.0, 1.0]
      - [dock, 0.45, 0.8, 0.0, 1.0]

      # - [path, 0.2, 0.4, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 0.2, 0.7, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 0.2, 1.0, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 0.2, 1.3, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 0.2, 1.6, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]

      # - [path, 0.4, 1.6, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 0.4, 1.3, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 0.4, 1.0, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 0.4, 0.7, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 0.4, 0.4, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]

      # - [path, 0.6, 0.4, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 0.6, 0.7, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 0.6, 1.0, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 0.6, 1.3, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]

      # - [path, 0.8, 1.3, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 0.8, 1.0, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 0.8, 0.7, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 0.8, 0.4, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]

      # - [path, 1.0, 0.4, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 1.0, 0.7, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 1.0, 1.0, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 1.0, 1.3, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]

      # - [path, 1.2, 1.3, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 1.2, 1.0, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 1.2, 0.7, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 1.2, 0.4, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]

      # - [path, 1.4, 0.4, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 1.4, 0.7, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 1.4, 1.0, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 1.4, 1.3, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]

      # - [path, 1.6, 1.3, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 1.6, 1.0, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 1.6, 0.7, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 1.6, 0.4, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]

      # - [path, 1.8, 0.4, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 1.8, 0.7, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 1.8, 1.0, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 1.8, 1.3, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      
      # - [path, 2.0, 1.3, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 2.0, 1.0, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 2.0, 0.7, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 2.0, 0.4, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]

      # - [path, 2.2, 0.4, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 2.2, 0.7, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 2.2, 1.0, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 2.2, 1.3, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]

      # - [path, 2.4, 1.3, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 2.4, 1.0, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 2.4, 0.7, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 2.4, 0.4, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]

      # - [path, 2.6, 0.4, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 2.6, 0.7, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 2.6, 1.0, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 2.6, 1.3, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 2.6, 1.6, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]

      # - [path, 2.8, 1.6, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 2.8, 1.3, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 2.8, 1.0, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 2.8, 0.7, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      # - [path, 2.8, 0.4, 0.0, 1.0]
      # - [wait, 20.0, 0.0, 0.0, 0.0]
      